import Head from 'next/head';
import { Footer } from './footer/Footer';
import { links } from '../constants/footerLinksData';

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
      <Footer data={links} />
    </>
  );
}
